
development:
  adapter: postgresql
  encoding: unicode
  database: {{app_name}}_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: {{app_name}}_test
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: {{app_name}}_development
  pool: 5
  username: postgres
  password: password
